- alias: "Alles uit bij vertrek"
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_willem
    zone: zone.home
    event: leave
  action:
    - service: script.lampen_woonkamer_uit
    - service: script.lampen_slaapkamer2_uit
    - service: media_player.turn_off
      data:
        entity_id: media_player.living_room_tv

- alias: "Licht aan voor zonsopkomst"
  trigger:
    platform: time
    at: "06:35:00"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: 0.0
      - condition: state
        entity_id: device_tracker.owntracks_willem
        state: home
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    service: script.lampen_woonkamer_aan

- alias: "Licht aan bij zonsondergang of tv uit"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -0.5
    - platform: state
      entity_id: media_player.living_room_tv
      to: "off"
    - platform: state
      entity_id: media_player.living_room_tv
      to: "paused"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.owntracks_willem
        state: home
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: -0.5
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.living_room_tv
            state: "off"
          - condition: state
            entity_id: media_player.living_room_tv
            state: "paused"
  action:
    service: script.lampen_woonkamer_aan

- alias: "Licht aan bij thuiskomst"
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_willem
    zone: zone.home
    event: enter
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -0.5
  action:
    service: script.lampen_woonkamer_aan

- id: movie_time
  alias: "Movie Time"
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      to: "playing"
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -0.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.owntracks_willem
        state: home
      - condition: state
        entity_id: media_player.living_room_tv
        state: "playing"
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: -0.5
  action:
    - service: script.movie_mode

- id: ventilation_slider_update
  alias: "Ventilatie slider bijwerken"
  trigger:
    platform: state
    entity_id: sensor.ventilation_current_mode
  action:
     service: input_number.set_value
     data_template:
      entity_id: input_number.ventilation
      value: "{{ states.sensor.ventilation_current_mode.state }}"

- id: ventilation_low
  alias: "Ventileren stand 1"
  trigger:
    - platform: state
      entity_id: input_number.ventilation
      to: "1.0"
    - platform: numeric_state
      entity_id: sensor.badkamer_sensor_relative_humidity
      below: 66
  action:
    - service: script.ventilatie_stand1

- id: ventilation_medium
  alias: "Ventileren stand 2"
  trigger:
    - platform: state
      entity_id: input_number.ventilation
      to: "2.0"
    - platform: numeric_state
      entity_id: sensor.badkamer_sensor_relative_humidity
      above: 65
      below: 80
  action:
    - service: script.ventilatie_stand2

- id: ventilation_high
  alias: "Ventileren stand 3"
  trigger:
    - platform: state
      entity_id: input_number.ventilation
      to: "3.0"
    - platform: numeric_state
      entity_id: sensor.badkamer_sensor_relative_humidity
      above: 79
  action:
    - service: script.ventilatie_stand3
