- alias: "Update beschikbaar"
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
    - service: notify.push
      data:
        message: "Er is een update voor Home Assistant beschikbaar!"
        data:
          tag: update-notification

- alias: "Power failure"
  trigger:
    platform: state
    entity_id: sensor.long_power_failure_count
  action:
    - service: notify.push
      data:
        message: "Er heeft zich een langdurige stroomstoring voorgedaan."
        data:
          tag: power-failure

- alias: "Voltage sag"
  trigger:
    platform: state
    entity_id: sensor.voltage_sags_phase_l1
  action:
    - service: notify.push
      data:
        message: "Er was zojuist een voltage sag."
        data:
          tag: voltage-sag

- alias: "Voltage swell"
  trigger:
    platform: state
    entity_id: sensor.voltage_swells_phase_l1
  action:
    - service: notify.push
      data:
        message: "Er was zojuist een voltage swell."
        data:
          tag: voltage-swell

- alias: "Alles uit bij vertrek"
  trigger:
    platform: state
    entity_id: sensor.someone_home
    to: "False"
  action:
    - service: script.lampen_woonkamer_uit
    - service: script.lampen_slaapkamer2_uit
    - service: media_player.turn_off
      data:
        entity_id: media_player.living_room_tv
    - service: climate.set_preset_mode
      data:
        entity_id: climate.anna_thermostat
        preset_mode: away

- alias: "Thermostaat aan bij thuiskomst"
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_willem
    zone: zone.home
    event: enter
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.anna_thermostat
        preset_mode: home

- alias: "Licht aan voor zonsopkomst"
  trigger:
    platform: time
    at: "06:35:00"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: 0.0
      - condition: state
        entity_id: device_tracker.owntracks_willem
        state: home
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    service: script.lampen_woonkamer_aan

- alias: "Licht uit bij zonsopkomst"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation  }}"
      above: 3.0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.owntracks_willem
        state: home
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    service: script.lampen_woonkamer_uit
  
- alias: "Licht aan bij zonsondergang"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -0.5
    - platform: state
      entity_id: input_boolean.movie_mode
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.owntracks_willem
        state: home
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: -0.5
      - condition: state
        entity_id: input_boolean.movie_mode
        state: 'off'
  action:
    service: script.lampen_woonkamer_aan

- alias: "Licht aan bij thuiskomst"
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_willem
    zone: zone.home
    event: enter
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -0.5
  action:
    service: script.lampen_woonkamer_aan

- alias: "Licht dimmen"
  trigger:
    - platform: state
      entity_id: input_boolean.movie_mode
      to: 'on'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -0.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.owntracks_willem
        state: home
      - condition: state
        entity_id: input_boolean.movie_mode
        state: 'on'
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: -0.5
  action:
    service: script.lampen_woonkamer_dimmen

- alias: "Movie mode aan"
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    to: "playing"
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.movie_mode

- alias: "Movie mode uit"
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      to: "off"
    - platform: state
      entity_id: media_player.living_room_tv
      to: "paused"
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.movie_mode

- id: ventilation_slider_update
  alias: "Ventilatie slider bijwerken"
  trigger:
    platform: state
    entity_id: sensor.ventilation_current_mode
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.ventilation
      value: "{{ states.sensor.ventilation_current_mode.state }}"

- id: ventilation_low
  alias: "Ventileren stand 1"
  trigger:
    - platform: state
      entity_id: input_number.ventilation
      to: "1.0"
    - platform: numeric_state
      entity_id: sensor.badkamer_sensor_relative_humidity
      below: 56
  action:
    - service: script.ventilatie_stand1

- id: ventilation_medium
  alias: "Ventileren stand 2"
  trigger:
    - platform: state
      entity_id: input_number.ventilation
      to: "2.0"
    - platform: numeric_state
      entity_id: sensor.badkamer_sensor_relative_humidity
      above: 55
      below: 66
  action:
    - service: script.ventilatie_stand2

- id: ventilation_high
  alias: "Ventileren stand 3"
  trigger:
    - platform: state
      entity_id: input_number.ventilation
      to: "3.0"
    - platform: numeric_state
      entity_id: sensor.badkamer_sensor_relative_humidity
      above: 65
  action:
    - service: script.ventilatie_stand3

- id: trash_notification
  alias: "Vuilniszak buiten zetten notificatie"
  trigger:
    - platform: time
      at: '20:30:00'
  condition:
    condition: time
    weekday:
      - mon
  action:
    - service: notify.push
      data:
        message: "Vergeet niet de vuilniszak buiten te zetten!"
        data:
          tag: trash-notification

- id: trash_tts
  alias: "Vuilniszak buiten zetten tts reminder"
  trigger:
    - platform: time
      at: '07:10:00'
  condition:
    condition: time
    weekday:
      - tue
  action:
    - service: tts.google_translate_say
      entity_id: media_player.home_group
      data:
        message: 'Heb je de vuilniszak al buitengezet?'
        language: 'nl'
