homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
    switch.slaapkamer_2_lamp_switch_2:
      hidden: true
    sensor.ventilatie_previous_reading:
      hidden: true
  customize_glob:
    "sensor.*_dimmer_*_system*":
      hidden: true
    "sensor.*_exporting*":
      hidden: true
    "sensor.*_alarm_level*":
      hidden: true
    "sensor.*_alarm_type*":
      hidden: true
    "sensor.*_heat*":
      hidden: true
    "sensor.*_power_management*":
      hidden: true
    "sensor.*_sourcenodeid*":
      hidden: true
    "sensor.*_sensor_burglar":
      hidden: true
    "sensor.*_sensor_ultraviolet":
      hidden: true
    "sensor.*phase_l2":
      hidden: true
    "sensor.*phase_l3":
      hidden: true

#logger:
#  default: debug

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.11

system_health:

# Checks for available updates
updater:
  include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  purge_interval: 1
  purge_keep_days: 14

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - group
      - zwave

# View all events in a logbook
logbook:
  exclude:
    domains:
      - automation
      - group
      - zwave

# Track the sun
sun:

# Weather Prediction
weather:
  - platform: openweathermap
    api_key: !secret owm_api_key

binary_sensor:
  - platform: workday
    country: NL

# Text to speech
tts:
  platform: google_translate

zwave:
  usb_path: /dev/ttyUSB0

climate:
  - platform: anna
    name: Anna Thermostat
    username: smile
    password: !secret anna_password
    host: !secret anna_host
    scan_interval: 10

media_player:
  - platform: webostv
    host: !secret tv_host
    name: Living Room TV
    filename: webostv.conf
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac

switch: !include switches.yaml
sensor: !include sensors.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
script: !include scripts.yaml
automation: !include automations.yaml
group: !include groups.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /etc/ssl/certs/ca-certificates.crt

owntracks:
  max_gps_accuracy: 100
  secret: !secret owntracks_password

notify:
  - name: push
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: file
    name: sleepfilenotify
    filename: /config/sleep_times.txt

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_homegraph_api_key
  expose_by_default: false
  entity_config:
    switch.buddha_waterpomp_switch:
      name: Buddha Fountain
      expose: true
      room: Living room
    input_boolean.movie_mode:
      name: Movie Mode
      expose: true
      room: Living room
    light.staande_lamp_1_level:
      name: Standing light one
      expose: true
      room: Living room
    light.staande_lamp_2_level:
      name: Standing light two
      expose: true
      room: Living room
    media_player.living_room_tv:
      name: Living room tv
      expose: true
      room: Living room
    switch.slaapkamer_2_lamp_switch:
      name: Second bedroom light
      expose: true
      aliases:
        - tweede slaapkamer lamp
      room: Second bedroom
    script.bedtijd:
      name: Bedtime
      expose: true
      room: Living room
