homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize_glob:
    "sensor.*_alarm_level":
      hidden: true
    "sensor.*_alarm_type":
      hidden: true
    "sensor.*_sourcenodeid":
      hidden: true
    "sensor.*_sensor_burglar":
      hidden: true
    "sensor.*_sensor_ultraviolet":
      hidden: true

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  purge_interval: 7
  purge_keep_days: 14

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
weather:
  - platform: openweathermap
    api_key: !secret owm_api_key

binary_sensor:
  - platform: workday
    country: NL

# Text to speech
tts:
  platform: google

zwave:
  usb_path: /dev/ttyUSB0

media_player:
  - platform: webostv
    host: !secret tv_host
    mac: !secret tv_mac
    name: Living Room TV
    filename: webostv.conf

switch: !include switches.yaml
sensor: !include sensors.yaml
input_number: !include input_numbers.yaml
script: !include scripts.yaml
automation: !include automations.yaml
group: !include groups.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks
