- platform: openweathermap
  forecast: 1
  api_key: !secret owm_api_key
  monitored_conditions:
    - weather
    - temperature
    - humidity

- platform: template
  sensors:
    ventilation_current_mode:
      friendly_name: "Ventilatie Huidige Stand"
      value_template: >
        {% if (is_state('switch.ventilatie_switch_2', 'on')) %}
          3
        {% elif (is_state('switch.ventilatie_switch', 'on')) %}
          2
        {% else %} 
          1
        {% endif %}
      entity_id:
        - switch.ventilatie_switch_2
        - switch.ventilatie_switch

- platform: dsmr
  host: !secret dsmr_host
  port: !secret dsmr_port
  dsmr_version: 5
